"""add match caching fields

Revision ID: 21ffd51ee25f
Revises: 269a5c67b376
Create Date: 2026-08-23 00:36:15.638092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ffd51ee25f'
down_revision: Union[str, Sequence[str], None] = '269a5c67b376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'jobs',
        sa.Column('matched_skills', sa.JSON(), nullable=True)
    )
    op.add_column(
        'jobs',
        sa.Column('missing_skills', sa.JSON(), nullable=True)
    )
    op.add_column(
        'jobs',
        sa.Column('match_explanation', sa.Text(), nullable=True)
    )
    op.add_column(
        'jobs',
        sa.Column(
            'match_computed_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    op.add_column(
        'resumes',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    op.execute(
        "UPDATE resumes SET updated_at = created_at WHERE updated_at IS NULL"
    )

    op.alter_column(
        'resumes',
        'updated_at',
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'updated_at')
    op.drop_column('jobs', 'match_computed_at')
    op.drop_column('jobs', 'match_explanation')
    op.drop_column('jobs', 'missing_skills')
    op.drop_column('jobs', 'matched_skills')
    # ### end Alembic commands ###
